---
roles:
  - name: mamono210.ja_desktop
    src: https://github.com/ansible-roles-mamono210/ja_desktop.git
  - name: mamono210.vnc_server_install
    src: https://github.com/ansible-roles-mamono210/vnc_server_install.git
