---
roles:
  - name: mamono210.docker
    src: https://github.com/ansible-roles-mamono210/docker.git
  - name: mamono210.ja_desktop
    src: https://github.com/ansible-roles-mamono210/ja_desktop.git
  - name: mamono210.vim
    src: https://github.com/ansible-roles-mamono210/vim.git
  - name: mamono210.vnc_server
    src: https://github.com/ansible-roles-mamono210/vnc_server.git
